version: "3.9"
services:
  database:
    image: "postgres:latest"
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pickup
    volumes:
      - ./code/tables:/var/lib/postgresql/my_tables
      - ./code/sprocs:/var/lib/postgresql/my_sprocs
      - db-data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    container_name: admin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=cohen.andrew.n@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
volumes:
  db-data:
    driver: local
