version: "3.9"
services:
  database:
    image: "postgres:latest"
    container_name: database
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pickup
    volumes:
      - ./tables:/var/lib/postgresql/my_tables
      - ./sprocs:/var/lib/postgresql/my_sprocs
