version: "3.9"
services:
  database:
    image: "postgres:latest"
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pickup123
      POSTGRES_DB: pickup
    volumes:
      - ./code/tables:/var/lib/postgresql/my_tables
      - ./code/functions:/var/lib/postgresql/my_funcs
      - db-data:/var/lib/postgresql/data
    networks:
      - pickup
  database-test:
    image: "postgres:latest"
    container_name: database-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pickup123
      POSTGRES_DB: pickup
    volumes:
      - ./code/tables:/var/lib/postgresql/my_tables
      - ./code/functions:/var/lib/postgresql/my_funcs
      - db-data-test:/var/lib/postgresql/data
    networks:
      - pickup
  admin:
    image: dpage/pgadmin4
    container_name: admin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pickup.com
      - PGADMIN_DEFAULT_PASSWORD=pickup123
    networks:
      - pickup
volumes:
  db-data:
    driver: local
  db-data-test:
    driver: local
networks:
  pickup:
