name: Database Migration

on:
  push:
    branches: [ main ]
    paths:
      - db/migrations/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go run main.go
